{
 "title": "Valence",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(promproxy_metric_handler_detailed_requests, service)"
   },
   {
    "name": "LatencyPercentile",
    "label": "Latency Percentile",
    "query": "label_values(promproxy_metric_handler_detailed_requests, quantile)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory recommendations: $deployment",
   "type": "graph",
   "description": "Recommendations of Memory requests and limits to set for $deployment",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container_name=\"$deployment\"})",
     "legendFormat": "Observed Memory Value"
    },
    {
     "expr": "max(valence_recommendations_memory_requests{container_name=\"$deployment\"})",
     "legendFormat": "Recommended Memory Request"
    },
    {
     "expr": "max(valence_recommendations_memory_limits{container_name=\"$deployment\"})",
     "legendFormat": "Recommended Memory Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_memory_bytes{container=\"$deployment\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_memory_bytes{container=\"$deployment\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Cpu recommendations: $deployment",
   "type": "graph",
   "description": "Recommendations of CPU requests and limits to set for $deployment",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container_name=\"$deployment\"}[2m]))",
     "legendFormat": "Observed CPU Value"
    },
    {
     "expr": "max(valence_recommendations_cpu_requests{container_name=\"$deployment\"} / 1000)",
     "legendFormat": "Recommended CPU Request"
    },
    {
     "expr": "max(valence_recommendations_cpu_limits{container_name=\"$deployment\"} / 1000)",
     "legendFormat": "Recommended CPU Limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests_cpu_cores{container=\"$deployment\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits_cpu_cores{container=\"$deployment\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "HTTP Request Count: $deployment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "QpS" }
   ],
   "targets": [
    {
     "expr": "sum(increase(promproxy_metric_handler_detailed_requests_count{service=\"$deployment\"}[1m])) / 60",
     "legendFormat": "HTTP Queries Per Second"
    }
   ]
  },
  {
   "title": "HTTP Request Latency: $deployment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(promproxy_metric_handler_detailed_requests{service=\"$deployment\", quantile=\"$LatencyPercentile\", code!=\"502\"}[1m]))",
     "legendFormat": "HTTP Request Latency"
    }
   ]
  },
  {
   "title": "Replicas: $deployment",
   "type": "graph",
   "description": "Number of replicas observed and recommended for: $deployment",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "valence_recommendations_replicas{name=\"$deployment\"}",
     "legendFormat": "Recommended Replicas"
    },
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"$deployment\"}",
     "legendFormat": "Current Replicas"
    }
   ]
  }
 ]
}