{
 "title": "Valence Reporting",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(envoy_http_downstream_rq_total, service)"
   },
   { "name": "LatencyPercentile", "label": "Latency Percentile", "query": "0.5, 0.75, 0.9, 0.95, 0.99" }
  ]
 },
 "panels": [
  {
   "title": "Average Utilization (with Valence)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container_name=\"$deployment\"}[5m]))  / sum(valence_recommendations_cpu_requests{container_name=\"$deployment\"} / 1000)"
    }
   ]
  },
  {
   "title": "Average Utilization (without Valence)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container_name=\"$deployment\"}[5m]))  / sum(valence_original_cpu_requests{container_name=\"$deployment\"} / 1000)"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "SLO Violations" }
   ],
   "targets": [
    {
     "expr": "count_over_time((avg(histogram_quantile($LatencyPercentile, sum(rate(envoy_http_downstream_rq_time_bucket{service=\"$deployment\"}[30s])) by(le, pod))) > 500)[5m:1m])",
     "legendFormat": "SLO Violations"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Utilization %" }
   ],
   "targets": [
    { "expr": "1.0", "legendFormat": "Over Utilization" },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container_name=\"$deployment\"}[5m]))  / sum(valence_original_cpu_requests{container_name=\"$deployment\"} / 1000)",
     "legendFormat": "Original Utilization"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{container_name=\"$deployment\"}[5m]))  / sum(valence_recommendations_cpu_requests{container_name=\"$deployment\"} / 1000)",
     "legendFormat": "Valence Utilization"
    }
   ]
  }
 ]
}